services:
  listmonk:
    image: listmonk/listmonk:${LISTMONK_VERSION:?required}
    container_name: listmonk
    restart: unless-stopped
    command: /listmonk/entrypoint.sh
    volumes:
      - ./.docker/listmonk/uploads:/listmonk/uploads
      - ./.docker/listmonk/entrypoint.sh:/listmonk/entrypoint.sh:ro
      - ./.docker/listmonk/config/config.toml:/listmonk/config.toml:ro
    networks:
      - postgres-network
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Router
      - traefik.http.routers.listmonk.rule=Host(`${LISTMONK_SERVER_HOSTNAME:?required}`)
      - traefik.http.routers.listmonk.entrypoints=websecure
      - traefik.http.routers.listmonk.tls.certresolver=le-cloudflare
      - traefik.http.routers.listmonk.service=listmonk

      # API Router - IP kısıtlaması ile
      - traefik.http.routers.listmonk-api.rule=Host(`${LISTMONK_SERVER_HOSTNAME:?required}`) && PathPrefix(`/api/`)
      - traefik.http.routers.listmonk-api.entrypoints=websecure
      - traefik.http.routers.listmonk-api.tls.certresolver=le-cloudflare
      - traefik.http.routers.listmonk-api.service=listmonk
      - traefik.http.routers.listmonk-api.priority=100
      - traefik.http.routers.listmonk-api.middlewares=trusted@file

      # Service
      - traefik.http.services.listmonk.loadbalancer.server.port=9000
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9000" ]
      interval: 30s
      timeout: 5s
      retries: 5


networks:
  postgres-network:
    external: true
  traefik-network:
    external: true
