services:
  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk
    restart: unless-stopped
    # İlk kurulum ve yükseltme işlemlerini tek bir komutla gerçekleştirmek için aşağıdaki
    # komutu kullanabilirsiniz. Bu komut, listmonk'u kurar, yükseltir ve ardından başlatır.
    command: >
      sh -c "
      ./listmonk --install --yes &&
      ./listmonk --upgrade --yes &&
      ./listmonk
      "
    # İlk kurulumdan sonra sadece listmonk'u başlatmak için aşağıdaki komutu kullanabilirsiniz.
    # command: ./listmonk
    volumes:
      - ./.docker/listmonk/uploads:/listmonk/uploads
      - ./.docker/listmonk/config/config.toml:/listmonk/config.toml:ro
    networks:
      - postgres-network
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Router
      - traefik.http.routers.listmonk.rule=Host(`${LISTMONK_SERVER_HOSTNAME:?required}`)
      - traefik.http.routers.listmonk.entrypoints=websecure
      - traefik.http.routers.listmonk.tls.certresolver=le-cloudflare
      - traefik.http.routers.listmonk.service=listmonk

      # API Router - IP kısıtlaması ile
      - traefik.http.routers.listmonk-api.rule=Host(`${LISTMONK_SERVER_HOSTNAME:?required}`) && PathPrefix(`/api/`)
      - traefik.http.routers.listmonk-api.entrypoints=websecure
      - traefik.http.routers.listmonk-api.tls.certresolver=le-cloudflare
      - traefik.http.routers.listmonk-api.service=listmonk
      - traefik.http.routers.listmonk-api.priority=100
      - traefik.http.routers.listmonk-api.middlewares=listmonk-api-ipwhitelist

      # API IP Whitelist Middleware
      - traefik.http.middlewares.listmonk-api-ipwhitelist.ipallowlist.sourcerange=${LISTMONK_API_ALLOWED_IPS}
      - traefik.http.middlewares.listmonk-api-ipwhitelist.ipallowlist.ipstrategy.depth=1

      # Service
      - traefik.http.services.listmonk.loadbalancer.server.port=9000
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9000" ]
      interval: 30s
      timeout: 5s
      retries: 5


networks:
  postgres-network:
    external: true
  traefik-network:
    external: true
